version: '3.1'

services:

  db:
    image: mysql:8.3.0
      #    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: picpay
      MYSQL_DATABASE: bancopicpay
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
